# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 214cf17c181cf0687a66fb84c37ae4e4cf12ebb662d1dbfe0edd72d3607767bba96424b1b6e2daf9e7850e43a03f718d92df42c1be2c68077f4f2492d8558106

test:
  secret_key_base: b45afaa78ac614492a1b2d7ce089018136de26b43de0007ff47fff74b5adea069e5ffd02aca73134737977e15b1d4fb93478068d33f35b9547ab0eb48f98312c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
